pre-commit
jupyter-xeus/cpp-terminal pull request #212
Opened 2022-12-20 05:19 UTC by flagarde

Add some pre-commit hooks.

I noted that the actual clang-format was not precise enough and allowed different formatting. I had a more precise one. Feel free to change parameters I you don't like the formatting.

2022-12-26 00:29 UTC, MCWertGaming requested changes
Looks really good, but I have added a note. When it's resolved and the PR is rebased, we can merge it. Thank you!

2022-12-26 13:55 UTC, flagarde commented
sorry I don't see your note. What do you want me to change ?

2023-01-01 14:24 UTC, MCWertGaming commented
Sorry @flagarde, it looks fine! Thank you really much for doing this PR.

2023-01-01 14:25 UTC, MCWertGaming approved these changes

2023-01-01 14:25 UTC, merged