Badstate  (Fix #248)
jupyter-xeus/cpp-terminal pull request #251
Opened 2023-05-17 00:47 UTC by flagarde

This PR fix #248 by doing : 
1) All the exceptions in the destructor are catch inside it to avoid the exception to leak...
2) A message is printed to say the terminal is not in good state with reasons if possible
3) Return EXIT_FAILURE to the parent or the value given by the environment variable CPP_TERMINAL_BADSTATE if it can be casted to int otherwise return the default value (EXIT_FAILURE). It can be possible to do:

UNIX :
```bash
./examples/keys ; echo $?
``` 
Windows : 
```cmd
.\examples\keys
echo %errorlevel%
```
to check if the terminal is in good mode.

I think it's the safest way to avoid crash and to let the user know something bad happened and to perform correction if he can/want/should.

2023-05-17 01:37 UTC, flagarde commented
@MCWertGaming the CI crashing is a fake negative, please rerun it

2023-05-24 08:04 UTC, MCWertGaming requested changes
I have added a comment. I'm not yet sure though what this PR should implement. Are you trying to catch exceptions internally to store it into some internal variables?

2023-05-24 11:21 UTC, flagarde commented on cpp-terminal/platforms/env.cpp
> +  return {true, ret};
on linux it seems you can have a empty value 
```bash
export TOTO=
```

so you need to check if the env is here and then the value.

2023-05-24 11:25 UTC, flagarde commented
> I have added a comment. I'm not yet sure though what this PR should implement. Are you trying to catch exceptions internally to store it into some internal variables?

This is to solve the problem that the terminal destructor let exception to go out of scope which is dangerous. see #248 for discution. It is impossible to let the software now the destructor had some problem so what I did based on the comment in #248 is : 

1) Warn the user with message
2) Let the program exit with a errorcode the user/system/a script can check to see if the terminal is in a good state otherwise depending on the OS teh user could perform some action by himself

2023-05-25 08:29 UTC, MCWertGaming commented on cpp-terminal/platforms/env.cpp
> +  return {true, ret};
Okay, I see it now ^^ may you add a comment to the function that explains the return values?

2023-05-25 08:30 UTC, MCWertGaming commented
Thanks, I see the context and problematic now. We can merge this when you added the function comment.

2023-05-25 18:13 UTC, flagarde commented on cpp-terminal/platforms/env.cpp
> +  return {true, ret};
Sure !

2023-05-26 11:09 UTC, flagarde commented
@MCWertGaming basic doxygen doc has been added

2023-06-09 09:29 UTC, flagarde commented
@MCWertGaming Do you agree to the changes ?

2023-06-28 11:24 UTC, flagarde commented
@certik Do you agree to this change ? I would like to merge this because I plan to clean a bit the terminal and have : 

```cpp
Term::Termout<<"f";
Term::Termlog<<"f";
Term::Termerr<<"f";
```

What about the name Termout, Termlog, Termerr ? Maybe tcout, tclog, terr ? Other ideas

which requires so organisation changes in the code

2023-07-01 12:27 UTC, merged